# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2'
services:
  api-php:
    environment:
      PHP_ENABLE_XDEBUG: 1
    ports:
      - '8337:80'
    volumes:
      - api/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  backend-php:
    environment:
      PHP_ENABLE_XDEBUG: 1
    ports:
      - '8338:80'
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - backend/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  db:
    volumes:
      - ./runtime/mariadb-data:/var/lib/mysql
    ports:
      - '3386:3306'

  mailcatcher:
    ports:
      - '8055:1080'
